import { Bot, FileQuestion, Loader2, Send } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import type { Conversation, Document, Message } from "../../lib/api";
import { api } from "../../lib/api";
import { Button } from "../ui/Button";
import { MessageBubble } from "./MessageBubble";

function temporaryMessage(role: Message["role"], content: string, conversationId: string): Message { return { id: `temp-${Date.now()}`, conversation_id: conversationId, role, content, citations: [], latency_ms: null, created_at: new Date().toISOString() }; }

export function ChatPanel({ conversationId, initialMessages, documents, onConversationCreated }: { conversationId: string | null; initialMessages: Message[]; documents: Document[]; onConversationCreated: (conversation: string) => void }) {
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [query, setQuery] = useState("");
  const [documentId, setDocumentId] = useState<string>("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => setMessages(initialMessages), [initialMessages, conversationId]);
  useEffect(() => bottomRef.current?.scrollIntoView({ behavior: "smooth" }), [messages]);

  const submit = async (event?: FormEvent) => { event?.preventDefault(); const text = query.trim(); if (!text || busy) return; setQuery(""); setBusy(true); setError(null); const localConversation = conversationId || "pending"; const userMessage = temporaryMessage("user", text, localConversation); const streamMessage = temporaryMessage("assistant", "", localConversation); setMessages((current) => [...current, userMessage, streamMessage]); let streamId = streamMessage.id;
    try { await api.streamChat({ query: text, document_id: documentId || null, conversation_id: conversationId }, { onToken: (content) => setMessages((current) => current.map((item) => item.id === streamId ? { ...item, content: item.content + content } : item)), onDone: (done) => { onConversationCreated(done.conversation_id); setMessages((current) => current.map((item) => item.id === streamId ? { ...item, id: done.message_id, conversation_id: done.conversation_id, content: done.answer, citations: done.citations, latency_ms: done.latency_ms } : item)); }, onError: (message) => setError(message) }); } catch (err) { setError(err instanceof Error ? err.message : "Không thể gửi câu hỏi"); setMessages((current) => current.filter((item) => item.id !== streamId)); } finally { setBusy(false); }
  };
  return <div className="flex min-h-[calc(100vh-9rem)] flex-col rounded-2xl border border-white/[0.08] bg-panel/45"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-3 sm:px-5"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-primary-500/15 text-primary-300"><Bot className="h-4 w-4" /></div><div><p className="text-sm font-medium text-white">StudyRAG AI</p><p className="text-[11px] text-emerald-300">Sẵn sàng hỗ trợ bạn</p></div></div><select value={documentId} onChange={(e) => setDocumentId(e.target.value)} className="max-w-[180px] rounded-lg border border-white/10 bg-white/[0.04] px-2.5 py-2 text-xs text-slate-400 outline-none sm:max-w-[240px]"><option value="">Tất cả tài liệu</option>{documents.filter((doc) => doc.status === "ready").map((doc) => <option value={doc.id} key={doc.id}>{doc.title}</option>)}</select></div><div className="flex-1 space-y-4 overflow-y-auto px-4 py-5 sm:px-6">{messages.length === 0 && <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-primary-500/10 text-primary-300"><FileQuestion className="h-7 w-7" /></div><h2 className="mt-5 text-lg font-medium text-white">Bạn muốn tìm hiểu điều gì?</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-600">Hỏi về công thức, bài tập, khái niệm trong tài liệu đã upload. Câu trả lời luôn đi kèm nguồn tham khảo.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{["Tóm tắt chương này", "Giải thích công thức quan trọng", "Tạo câu hỏi ôn tập"].map((suggestion) => <button key={suggestion} onClick={() => setQuery(suggestion)} className="rounded-lg border border-white/[0.08] px-3 py-2 text-xs text-slate-500 hover:border-primary-300/20 hover:text-slate-300">{suggestion}</button>)}</div></div>}{messages.map((message) => <MessageBubble key={message.id} message={message} streaming={busy && message.role === "assistant" && message.id.startsWith("temp-")} />)}{error && <p className="rounded-xl bg-rose-400/10 px-3 py-2 text-xs text-rose-300">{error}</p>}<div ref={bottomRef} /></div><form onSubmit={submit} className="border-t border-white/[0.07] p-3 sm:p-4"><div className="flex items-end gap-2 rounded-xl border border-white/10 bg-white/[0.03] p-2 focus-within:border-primary-400/50"><textarea value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void submit(); } }} rows={1} placeholder="Đặt câu hỏi về tài liệu…" className="max-h-32 min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm text-white outline-none placeholder:text-slate-600" /><Button type="submit" size="sm" disabled={busy || !query.trim()}>{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</Button></div><p className="mt-2 px-1 text-[10px] text-slate-700">Enter để gửi · Shift + Enter để xuống dòng</p></form></div>;
}
